### ISSUE TITLE
epic 10

### ISSUE THREAD

**Issue by kn185097** [kn-jack-bot-testing/jack-bot#104]
___
### Issues

- [ ]   #147 - cgvhkbjl
- [ ]   #148 - dfyguhij
- [ ]   #323 - chgvjbkn
- [ ]   #324 - serdrtftygy
- [ ]   #325 - hgjh
- [ ]   #326 - fghvjhb
- [ ]   #327 - cghjvhb
- [ ]   #328 - fhgjh
- [ ]   #329 - vjhbkjnl
- [ ]   #330 - cfhgv
- [ ]   #332 - fagerhkjnr
- [ ]   #333 - gjhkjnlk
- [ ]   #335 - fcgvjhb
- [ ]   #338 - gjhkjl
- [ ]   #348 - size and issue same time
- [ ]   #349 - invalid size and issue same time
- [ ]   #350 - issue and then size
- [ ]   #351 - size and issue in comments
- [ ]   #352 - invalid size and issue in comments
- [ ]   #362 - gvhbj
- [ ]   #365 - multi issues and sizes
- [ ]   #371 - ftyugyh
- [ ]   #396 - vbmn
- [ ]   #397 - tndyrst
- [ ]   #398 - cfhgvjhb
- [ ]   #399 - hgvjhbkjn
- [ ]   #415 - vhbkjn
- [ ]   #418 - vgjhbknlm
- [ ]   #441 - drfgjhk
- [ ]   #442 - fgjhkn
- [ ]   #444 - gghjknlm
- [ ]   #445 - vhbmn,m
- [ ]   #446 - cfgvnmn
- [ ]   #447 - cfhgvjhb
- [ ]   #448 - vnbmnm
- [ ]   #449 - cfgnvhmb
- [ ]   #450 - gvhjhbj
- [ ]   #451 - hvgbjkn
- [ ]   #458 - gvhmbj
- [ ]   #472 - dcfghgvjhbk
- [x]   #149 - fyguhkj
- [x]   #160 - dxtfghjkj
- [x]   #165 - edtrfyguiho
- [x]   #188 - fxdgfchgvjhbkjlk
- [x]   #372 - drtftgyh
- [x]   #400 - vgnbm n

 To add an issue to this list use the command `/issue #{issue_number}` in the comments of an issue.
[Click here to find out more about jackbot](https://github.com/apps/ncr-jackbot)
___
